name: Nix build

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
    paths:
    - '**.cabal'
    - 'src/**'
    - 'test/**'
  pull_request:
    branches: [ master ]
    paths:
    - '**.cabal'
    - 'src/**'
    - 'test/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Cachix
        uses: cachix/cachix-action@v6
        with:
          # Name of a cachix cache to push and pull/substitute
          name: lastpass-tui
          authToken: ${{ secrets.AUTH_TOKEN }}
          # Signing key secret retrieved after creating binary cache on https://cachix.org
          signingKey: ${{ secrets.SIGNING_KEY }}
          # Set to true to disable pushing build results to the cache
          skipPush: false
    
      # Runs a single command using the runners shell
      - name: Build executable through nix
        run: nix-build -A lastpass-tui.components.exes.lpt
