name: Nix build

on:
  pull_request:
    branches: [ master ]
    paths:
    - '**.cabal'
    - 'src/**'
    - 'test/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: cachix/install-nix-action@v10
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Cachix
        uses: cachix/cachix-action@v6
        with:
          name: lastpass-tui
          authToken: ${{ secrets.AUTH_TOKEN }}
          signingKey: ${{ secrets.SIGNING_KEY }}
          # Set to true to disable pushing build results to the cache
          skipPush: false
          
      - name: Build executable through nix
        run: |
          cachix use iohk
          nix-build -A lastpass-tui.components.exes.lpt
